server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-person-service
          uri: lb://product-person-service
          predicates:
            - Path=/api/v2/accountbank/**
        - id: customer-person-service
          uri: lb://customer-person-service
          predicates:
            - Path=/api/v2/customerperson/**
        - id: customer-enterprise-service
          uri: lb://customer-enterprise-service
          predicates:
            - Path=/api/v2/customerenterprise/**