server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-accountbank
          uri: lb://service-accountbank
          predicates:
            - Path=/api/v2/accountbank/**